#!/usr/bin/env node
/**
 * Generates TypeScript types and constants from schema/events.schema.json.
 *
 * The JSON Schema file is the single source of truth for the wire protocol.
 * Edits must be made in the schema; regenerate this file with npm run generate.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const schemaPath = join(root, 'schema', 'events.schema.json')
const outPath = join(root, 'src', 'generated', 'protocol.ts')

const schema = JSON.parse(await readFile(schemaPath, 'utf8'))
const definitions = schema.definitions ?? {}

const pascal = (name) => name

function tsType(node) {
  if (node === undefined || node === null) return 'unknown'
  if (node.$ref) {
    return node.$ref.split('/').pop()
  }
  if (node.const !== undefined) return JSON.stringify(node.const)
  if (Array.isArray(node.enum) && node.enum.length > 0) {
    return node.enum.map((value) => JSON.stringify(value)).join(' | ')
  }
  if (Array.isArray(node.type)) {
    return node.type.map((t) => tsType({ ...node, type: t })).join(' | ')
  }
  switch (node.type) {
    case 'string':
      return 'string'
    case 'number':
      return 'number'
    case 'integer':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'array':
      return `Array<${tsType(node.items ?? {})}>`
    case 'object':
      if (node.properties) {
        return `{\n${Object.entries(node.properties)
          .map(([key, prop]) => {
            const optional = node.required?.includes(key) ? '' : '?'
            const comment = prop.description ? `  /** ${prop.description.replace(/\*\//g, '*\\/')} */\n` : ''
            return `${comment}  ${key}${optional}: ${tsType(prop)};`
          })
          .join('\n')}\n}`
      }
      return 'Record<string, unknown>'
    default:
      return 'unknown'
  }
}

function interfaceFor(name, node) {
  const fields = Object.entries(node.properties ?? {}).map(([key, prop]) => {
    const comment = prop.description ? `  /** ${prop.description.replace(/\*\//g, '*\\/')} */\n` : ''
    const optional = node.required?.includes(key) ? '' : '?'
    return `${comment}  ${JSON.stringify(key)}${optional}: ${tsType(prop)};`
  })
  const body = fields.length > 0 ? `\n${fields.join('\n')}\n` : ''
  return `export interface ${name} ${body.length > 0 ? `{${body}}` : '{}'}`
}

function scalarOrObjectFor(name, node) {
  if (node.type === 'object' || node.properties) {
    return interfaceFor(name, node)
  }
  return `export type ${name} = ${tsType(node)}`
}

const lines = [
  '/* This file is generated by scripts/generate-types.mjs from schema/events.schema.json. Do not edit. */',
  '/* eslint-disable */',
  '',
  ...Object.entries(definitions).map(([name, node]) => scalarOrObjectFor(name, node)),
  '',
  `export type PetEvent = ${schema.oneOf
    .map((entry) => entry.$ref.split('/').pop())
    .join(' | ')}`,
  '',
  `export const EVENT_TYPES = [${schema.oneOf
    .map((entry) => {
      const name = entry.$ref.split('/').pop()
      return JSON.stringify(definitions[name]?.properties?.type?.const)
    })
    .filter((value) => value !== undefined)
    .join(', ')}] as const`,
  '',
  'export type EventType = (typeof EVENT_TYPES)[number]',
  '',
  `export const protocolSchema = ${JSON.stringify(schema, null, 2)}`,
  '',
]

await mkdir(dirname(outPath), { recursive: true })
await writeFile(outPath, lines.join('\n'), 'utf8')
console.log(`generated ${outPath}`)
